### ISSUE TITLE
SyntaxError: missing ) after argument list

### ISSUE THREAD

**Issue by e-stonia** [blackfoot-makers/node-nextcloud#1]
My code (od course with my domain and user/pass:

```
const NextCloud = require('nextcloud');
var nc = NextCloud("cloud.mydomain.com", "admin", "mypass");

// Create user "toto"
nc.users.add("toto", "awesomePassword!", (err, ocs) => {
    // Check for server error
    if (err) {
        console.error(err);
    }
    // Check API status code
    else if (ocs.meta.statuscode != 100) {
        console.error(`Nextcloud error ${ocs.meta.statuscode}: ${ocs.meta.message}`);
    }
    else {
        console.log("User created!");   
    }
}
```
And this is what I get:

```
C:\apps\crm\_node>node index.js
C:\apps\crm\_node\index.js:17
}
^

SyntaxError: missing ) after argument list
[90m    at wrapSafe (internal/modules/cjs/loader.js:1053:16)[39m
[90m    at Module._compile (internal/modules/cjs/loader.js:1101:27)[39m
[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)[39m
[90m    at Module.load (internal/modules/cjs/loader.js:985:32)[39m
[90m    at Function.Module._load (internal/modules/cjs/loader.js:878:14)[39m
[90m    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)[39m
[90m    at internal/main/run_main_module.js:17:47[39m
```

On install I got some warnings:

```
C:\apps\crm\_node>npm install --save node-nextcloud
npm WARN saveError ENOENT: no such file or directory, open 'C:\apps\crm\_node\package.json'
npm WARN enoent ENOENT: no such file or directory, open 'C:\apps\crm\_node\package.json'
npm WARN _node No description
npm WARN _node No repository field.
npm WARN _node No README data
npm WARN _node No license field.

+ node-nextcloud@1.1.2
added 1 package from 1 contributor and audited 354 packages in 3.332s

5 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


C:\apps\crm\_node>npm fund
C:\apps\crm\_node
+-- https://github.com/sponsors/isaacs
| `-- glob@7.1.6
+-- https://github.com/sponsors/ljharb
| `-- resolve@1.17.0
+-- https://github.com/sponsors/feross
| `-- safe-buffer@5.2.1, simple-concat@1.0.1
+-- https://www.patreon.com/feross
| `-- safe-buffer@5.2.1, simple-concat@1.0.1
+-- https://feross.org/support
| `-- safe-buffer@5.2.1, simple-concat@1.0.1
`-- https://github.com/sponsors/epoberezkin
  `-- ajv@6.12.6
```

I have Node v12.18.4

**Comment by atomheartother** [comment]
There is indeed a missing parenthesis at the end of the example file, thanks!
